// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Cliente
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("CPF")]
        [StringLength(13)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Endereco { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Cidade { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Bairro { get; set; }
        [Column("CEP")]
        [StringLength(8)]
        [Unicode(false)]
        public string Cep { get; set; }
        [Column("RG")]
        [StringLength(7)]
        [Unicode(false)]
        public string Rg { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string EmailPrincipal { get; set; }
        [Column("Complemento_Logradouro")]
        [StringLength(50)]
        [Unicode(false)]
        public string ComplementoLogradouro { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string Telefone { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string Cel { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Naturalidade { get; set; }
        [Column("Nome_Mae")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeMae { get; set; }
        [Column("Nome_Pai")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomePai { get; set; }
        public bool Ativo { get; set; }
        [Column("Data_do_Cadastro")]
        public DateTime? DataDoCadastro { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Observacao { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Profissao { get; set; }
        [Column("Renda_Mensal")]
        public float? RendaMensal { get; set; }
        [Column("Tipo_de_Pessoa")]
        public int TipoDePessoa { get; set; }
        [Column("CNPJ")]
        [StringLength(14)]
        [Unicode(false)]
        public string Cnpj { get; set; }
        [Column("Codigo_Cliente")]
        [StringLength(50)]
        [Unicode(false)]
        public string CodigoCliente { get; set; }
    }
}