// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Comanda
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(18)]
        [Unicode(false)]
        public string Codigo { get; set; }
        [Column("Id_Mesa")]
        public int IdMesa { get; set; }
        [Column("Id_Produto")]
        public int IdProduto { get; set; }
        [Column("Id_Usuario")]
        public int IdUsuario { get; set; }

        [ForeignKey("IdMesa")]
        [InverseProperty("Comanda")]
        public virtual Mesa IdMesaNavigation { get; set; }
        [ForeignKey("IdProduto")]
        [InverseProperty("Comanda")]
        public virtual Produto IdProdutoNavigation { get; set; }
        [ForeignKey("IdUsuario")]
        [InverseProperty("Comanda")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}