// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Empresa
    {
        public Empresa()
        {
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        public int Id { get; set; }
        [Column("Nome_Fantasia")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeFantasia { get; set; }
        [StringLength(14)]
        [Unicode(false)]
        public string Codigo { get; set; }
        [Column("Razao_Social")]
        [StringLength(50)]
        [Unicode(false)]
        public string RazaoSocial { get; set; }
        [Column("Cnae_Fiscal")]
        [StringLength(7)]
        [Unicode(false)]
        public string CnaeFiscal { get; set; }
        [Column("CNPJ")]
        [StringLength(14)]
        [Unicode(false)]
        public string Cnpj { get; set; }
        public bool Ativo { get; set; }
        [Column("Inscricao_Estadual")]
        [StringLength(20)]
        [Unicode(false)]
        public string InscricaoEstadual { get; set; }
        [Column("Inscricao_Municipal")]
        [StringLength(20)]
        [Unicode(false)]
        public string InscricaoMunicipal { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column(TypeName = "text")]
        public string Telefone { get; set; }
        [Column(TypeName = "text")]
        public string Celular { get; set; }

        [InverseProperty("IdEmpresaNavigation")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}