// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Estoque
    {
        public Estoque()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        public int Id { get; set; }
        [Column("Quantidade_Atual", TypeName = "numeric(18, 0)")]
        public decimal? QuantidadeAtual { get; set; }
        [Column("Quantidade_Disponivel", TypeName = "numeric(18, 0)")]
        public decimal? QuantidadeDisponivel { get; set; }
        [Column("Quantidade_Reservada", TypeName = "numeric(18, 0)")]
        public decimal? QuantidadeReservada { get; set; }
        [Column("Id_Setor_Estoque")]
        public int IdSetorEstoque { get; set; }

        [ForeignKey("IdSetorEstoque")]
        [InverseProperty("Estoque")]
        public virtual SetorDoEstoque IdSetorEstoqueNavigation { get; set; }
        [InverseProperty("IdEstoqueProdutoNavigation")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}