// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("CNPJ")]
        [StringLength(14)]
        [Unicode(false)]
        public string Cnpj { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string Codigo { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Endereco { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Cidade { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Bairro { get; set; }
        [Column("CEP")]
        [StringLength(8)]
        [Unicode(false)]
        public string Cep { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column("Complementeo_Endereco")]
        [StringLength(50)]
        [Unicode(false)]
        public string ComplementeoEndereco { get; set; }
        [Column("Razao_Social")]
        [StringLength(50)]
        [Unicode(false)]
        public string RazaoSocial { get; set; }
        [Column("CNAE")]
        [StringLength(7)]
        [Unicode(false)]
        public string Cnae { get; set; }
        [Column("Inscricao_Estadual")]
        [StringLength(20)]
        [Unicode(false)]
        public string InscricaoEstadual { get; set; }
        [Column("Inscricao_Municipal")]
        [StringLength(20)]
        [Unicode(false)]
        public string InscricaoMunicipal { get; set; }
        public bool Ativo { get; set; }
        [Column("Tipo_de_Pessoa")]
        public int TipoDePessoa { get; set; }
        [Column("Email_DANFE")]
        [StringLength(50)]
        [Unicode(false)]
        public string EmailDanfe { get; set; }
        [Column("CPF")]
        [StringLength(13)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string Telefone { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string Celular { get; set; }
        [Column(TypeName = "text")]
        public string Observacoes { get; set; }

        [InverseProperty("IdFornecedorNavigation")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}