// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Marca
    {
        public Marca()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string Codigo { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string Nome { get; set; }
        public bool Ativa { get; set; }

        [InverseProperty("IdMarcaProdutoNavigation")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}