// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Mesa
    {
        public Mesa()
        {
            Comanda = new HashSet<Comanda>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(18)]
        [Unicode(false)]
        public string Codigo { get; set; }

        [InverseProperty("IdMesaNavigation")]
        public virtual ICollection<Comanda> Comanda { get; set; }
    }
}