// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Produto
    {
        public Produto()
        {
            Comanda = new HashSet<Comanda>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("Codigo_Principal")]
        [StringLength(20)]
        [Unicode(false)]
        public string CodigoPrincipal { get; set; }
        [Column("Codigo_Barras")]
        [StringLength(20)]
        [Unicode(false)]
        public string CodigoBarras { get; set; }
        [Column("Permitir_Venda")]
        public bool PermitirVenda { get; set; }
        public bool Inativo { get; set; }
        [Column("Controla_Estoque")]
        public bool ControlaEstoque { get; set; }
        [Column(TypeName = "text")]
        public string Observacao { get; set; }
        [Column("Id_Estoque_Produto")]
        public int IdEstoqueProduto { get; set; }
        [Column("Id_Marca_Produto")]
        public int? IdMarcaProduto { get; set; }
        [Column("id_Secao_Produto")]
        public int? IdSecaoProduto { get; set; }
        [Column("Id_Fornecedor")]
        public int? IdFornecedor { get; set; }

        [ForeignKey("IdEstoqueProduto")]
        [InverseProperty("Produto")]
        public virtual Estoque IdEstoqueProdutoNavigation { get; set; }
        [ForeignKey("IdFornecedor")]
        [InverseProperty("Produto")]
        public virtual Fornecedor IdFornecedorNavigation { get; set; }
        [ForeignKey("IdMarcaProduto")]
        [InverseProperty("Produto")]
        public virtual Marca IdMarcaProdutoNavigation { get; set; }
        [ForeignKey("IdSecaoProduto")]
        [InverseProperty("Produto")]
        public virtual Secao IdSecaoProdutoNavigation { get; set; }
        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<Comanda> Comanda { get; set; }
    }
}