// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    [Table("Setor_do_Estoque")]
    public partial class SetorDoEstoque
    {
        public SetorDoEstoque()
        {
            Estoque = new HashSet<Estoque>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Codigo { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        public bool Ativo { get; set; }

        [InverseProperty("IdSetorEstoqueNavigation")]
        public virtual ICollection<Estoque> Estoque { get; set; }
    }
}