// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WSPlus.DATA.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Comanda = new HashSet<Comanda>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Senha { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string Telefone { get; set; }
        [Column("Id_Empresa")]
        public int IdEmpresa { get; set; }
        [Column("Id_Atendente")]
        public int? IdAtendente { get; set; }

        [ForeignKey("IdAtendente")]
        [InverseProperty("Usuario")]
        public virtual Atendente IdAtendenteNavigation { get; set; }
        [ForeignKey("IdEmpresa")]
        [InverseProperty("Usuario")]
        public virtual Empresa IdEmpresaNavigation { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Comanda> Comanda { get; set; }
    }
}